pig_homepage:
    path:     /
    defaults: { _controller: EmpleadasBundle:Default:index }

clientes_index:
    path:     /clientes
    defaults: { _controller: PIGBundle:Cliente:index }

clientes_nuevo:
    path:     /clientes/new
    defaults: { _controller: PIGBundle:Cliente:nuevoCliente }

clientes_borrar:
    path:     /clientes/delete/{id}
    defaults: { _controller: PIGBundle:Cliente:borrar }

clientes_todos:
    path:     /clientes/all
    defaults: { _controller: PIGBundle:Cliente:clienteAll }

clientes_show:
    path:     /clientes/show/{id}
    defaults: { _controller: PIGBundle:Cliente:clienteShow }

clientes_exito:
    path:     /clientes/msgExito
    defaults: { _controller: PIGBundle:Cliente:msgExito }

trabajadoras_index:
    path:     /trabajadoras
    defaults: { _controller: PIGBundle:Trabajadora:index }

trabajadoras_nueva:
    path:     /trabajadoras/new
    defaults: { _controller: PIGBundle:Trabajadora:nuevaTrabajadora }

trabajadoras_borrar:
    path:     /trabajadoras/delete/{id}
    defaults: { _controller: PIGBundle:Trabajadora:borrar }

trabajadoras_todas:
    path:     /trabajadoras/show/{id}
    defaults: { _controller: PIGBundle:Trabajadora:trabajadoraShow }

trabajadoras_horario:
    path:     /trabajadoras/horario/{id}
    defaults: { _controller: PIGBundle:Trabajadora:trabajadoraHorario }

trabajadoras_exito:
    path:     /trabajadoras/msgExito
    defaults: { _controller: PIGBundle:Trabajadora:msgExito }


Servicios_index:
    path:     /servicios
    defaults: { _controller: PIGBundle:Servicio:index }

Servicios_nuevo:
    path:     /servicios/new
    defaults: { _controller: PIGBundle:Servicio:nuevoServicio }

Asignar_Empleada:
    path:     /servicios/asignar/{trabajadora}/{servicio}
    defaults: { _controller: PIGBundle:Servicio:asignar }

Servicios_borrar:
    path:     /servicios/delete/{id}
    defaults: { _controller: PIGBundle:Servicio:borrar }

Servicios_todos:
    path:     /servicios/all
    defaults: { _controller: PIGBundle:Servicio:servicioAll }

Servicios_show:
    path:     /servicios/show/{id}
    defaults: { _controller: PIGBundle:Servicio:servicioShow }

Servicios_exito:
    path:     /servicios/msgExito
    defaults: { _controller: PIGBundle:Servicio:msgExito }

Otros_nuevo:
    path:     /servicios/newOtro/{id}
    defaults: { _controller: PIGBundle:Otro:nuevoOtro }

Mantenimientos_nuevo:
    path:     /servicios/newMantenimiento/{id}
    defaults: { _controller: PIGBundle:Mantenimiento:nuevoMantenimiento }

Caterings_nuevo:
    path:     /servicios/newCatering/{id}
    defaults: { _controller: PIGBundle:Catering:nuevoCatering }

Limpiezas_nuevo:
    path:     /servicios/newLimpieza/{id}
    defaults: { _controller: PIGBundle:Limpieza:nuevoLimpieza }

usuario_nuevo:
    path:     /register
    defaults: { _controller: PIGBundle:User:register }

admin_homepage:
    path:     /
    defaults: { _controller: PIGBundle:Default:index }

admin_login:
    path:     /login
    defaults: { _controller: PIGBundle:User:login}

logout:
    path:     /logout
